//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace SingingPractice.Database
{
	/// <summary>
	/// Database       : SingingPractice
	/// Data Source    : .
	/// Server Version : 15.00.2000
	/// </summary>
	public partial class SingingPracticeDb : LinqToDB.Data.DataConnection
	{
		public ITable<License> Licenses { get { return this.GetTable<License>(); } }

		public SingingPracticeDb()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public SingingPracticeDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Licenses")]
	public partial class License
	{
		[PrimaryKey, NotNull    ] public Guid      Id             { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string    KeyHash        { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public string    Salt           { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public DateTime  CreationDate   { get; set; } // datetime
		[Column,        Nullable] public DateTime? ActivationDate { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static License Find(this ITable<License> table, Guid Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
